version: "3.3"
services:
  flaskapp:
    build: ./app
    image: kiranrepository2023/flaskapp:latest
    ports:
      - "8030:8010"

  flaskapp1:
    build: ./app
    image: kiranrepository2023/flaskapp:latest
    ports:
      - "8020:8010"

